# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92688468abd045dd1c8dd9891f026780366058ec959dae0577a6d64f0234fd9d4e08f77ce951ba63713cbd4057d0b18efe06ab935b0699809099a2eac72dafc5

test:
  secret_key_base: 719c2ed120894041b4ccb1b2711ef9ca91812e80dc1bc74288f1e5d2177c15819833ac042a8a862f1ad67df2ff3babe3ebfdeb640e65336066398c0edeedfd51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
